### ISSUE TITLE
Error while creating a secure connection

### ISSUE THREAD

**Issue by moutonnoireu** [pretix/pretixdesk#42]
Hello, while trying to use the pretixdesk software, I got this error : 

```js
eu.pretix.libpretixsync.check.CheckException: Error while creating a secure connection.
	at eu.pretix.libpretixsync.check.OnlineCheckProvider.search(OnlineCheckProvider.java:149)
	at eu.pretix.pretixdesk.ui.MainController.handleSearchInput(MainController.kt:21)
	at eu.pretix.pretixdesk.ui.MainView$handleSearchInput$1.invoke(MainView.kt:518)
	at eu.pretix.pretixdesk.ui.MainView$handleSearchInput$1.invoke(MainView.kt:34)
	at tornadofx.FXTask.call(Async.kt:416)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I'm thinking that's my server who's maybe misconfigured but the https/ssl access is well configured. Any idea ? :(

**Comment by johan12345** [comment]
Hi, the actual SSLException that caused this issue should also have been printed in the log.

It probably is a server configuration issue - Java is often slightly more picky about correct configuration than web browsers. For example, an intermediate certificate might be missing. The test at https://www.ssllabs.com/ssltest/ might help to find the issue.
